### ISSUE TITLE
Enabling riru core mess up storage

### ISSUE THREAD

**Issue by Kiblyn11** [shakalaca/MagiskOnEmulator#1]
First, I want to say awesome job for that.

I use Android x86_64 9.0r2.
I did success to have Magisk and working modules.
I try to use Magisk + Riru Core + EdXposed and that seems to work OK.
But, there is one issue, the storage seems messed up. It is not possible to install APK anymore and Settings Storage says it's using 100% of space but it isn't (wasn't before enabling riru-core module).

![image](https://user-images.githubusercontent.com/4669951/83258343-63e08600-a1b6-11ea-8bb3-4091b14ba1c5.png)

and trying to install APK with ADB leads to:
```
Exception occurred while executing:
android.os.ParcelableException: java.io.IOException: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.os.IInstalld.isQuotaSupported(java.lang.String)' on a null object reference
	at android.util.ExceptionUtils.wrap(ExceptionUtils.java:34)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:406)
	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:2415)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:907)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:158)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21268)
	at android.os.Binder.shellCommand(Binder.java:634)
	at android.os.Binder.onTransact(Binder.java:532)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2796)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3856)
	at android.os.Binder.execTransact(Binder.java:731)
Caused by: java.io.IOException: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.os.IInstalld.isQuotaSupported(java.lang.String)' on a null object reference
	at com.android.server.usage.StorageStatsService.isQuotaSupported(StorageStatsService.java:163)
	at android.app.usage.StorageStatsManager.isQuotaSupported(StorageStatsManager.java:69)
	at android.app.usage.StorageStatsManager.isQuotaSupported(StorageStatsManager.java:78)
	at com.android.server.StorageManagerService.getAllocatableBytes(StorageManagerService.java:2916)
	at android.os.storage.StorageManager.getAllocatableBytes(StorageManager.java:1754)
	at com.android.internal.content.PackageHelper.resolveInstallVolume(PackageHelper.java:188)
	at com.android.internal.content.PackageHelper.resolveInstallVolume(PackageHelper.java:148)
	at com.android.internal.content.PackageHelper.resolveInstallVolume(PackageHelper.java:163)
	at com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:502)
	at com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:404)
	... 10 more

```

Is that related to your tricks ?

**Comment by shakalaca** [comment]
Looks good on my side, would you please list the precise steps in your setup ?

**Comment by Kiblyn11** [comment]
Well, I don't explain that but it seems that rebooting the VM fixed it, can't figure why.
Anyway, thanks.
